version: '2.3'

services:
  loki:
    build:
      context: .
      target: dev
    image: "loki"
    ports:
      - 8000:8000
    env_file:
      - envfiles/shared.env
    volumes:
      - "./:/var/www/main"
    command: "./bin/wait-for-it.sh postgres:5432 -- python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=monkfish
      - POSTGRES_DB=loki

  redis:
    image: redis:4-alpine
